// Generated by gencpp from file fetch_grasp_suggestion/AddObjectRequest.msg
// DO NOT EDIT!


#ifndef FETCH_GRASP_SUGGESTION_MESSAGE_ADDOBJECTREQUEST_H
#define FETCH_GRASP_SUGGESTION_MESSAGE_ADDOBJECTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/PointCloud2.h>
#include <geometry_msgs/Point.h>

namespace fetch_grasp_suggestion
{
template <class ContainerAllocator>
struct AddObjectRequest_
{
  typedef AddObjectRequest_<ContainerAllocator> Type;

  AddObjectRequest_()
    : point_clouds()
    , centroids()
    , indices()  {
    }
  AddObjectRequest_(const ContainerAllocator& _alloc)
    : point_clouds(_alloc)
    , centroids(_alloc)
    , indices(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::sensor_msgs::PointCloud2_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::sensor_msgs::PointCloud2_<ContainerAllocator> >> _point_clouds_type;
  _point_clouds_type point_clouds;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _centroids_type;
  _centroids_type centroids;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _indices_type;
  _indices_type indices;





  typedef boost::shared_ptr< ::fetch_grasp_suggestion::AddObjectRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fetch_grasp_suggestion::AddObjectRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddObjectRequest_

typedef ::fetch_grasp_suggestion::AddObjectRequest_<std::allocator<void> > AddObjectRequest;

typedef boost::shared_ptr< ::fetch_grasp_suggestion::AddObjectRequest > AddObjectRequestPtr;
typedef boost::shared_ptr< ::fetch_grasp_suggestion::AddObjectRequest const> AddObjectRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fetch_grasp_suggestion::AddObjectRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fetch_grasp_suggestion::AddObjectRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fetch_grasp_suggestion::AddObjectRequest_<ContainerAllocator1> & lhs, const ::fetch_grasp_suggestion::AddObjectRequest_<ContainerAllocator2> & rhs)
{
  return lhs.point_clouds == rhs.point_clouds &&
    lhs.centroids == rhs.centroids &&
    lhs.indices == rhs.indices;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fetch_grasp_suggestion::AddObjectRequest_<ContainerAllocator1> & lhs, const ::fetch_grasp_suggestion::AddObjectRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fetch_grasp_suggestion

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fetch_grasp_suggestion::AddObjectRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fetch_grasp_suggestion::AddObjectRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fetch_grasp_suggestion::AddObjectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fetch_grasp_suggestion::AddObjectRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fetch_grasp_suggestion::AddObjectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fetch_grasp_suggestion::AddObjectRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fetch_grasp_suggestion::AddObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bdc6bafe38a479a9ea4dff4f456ad1d5";
  }

  static const char* value(const ::fetch_grasp_suggestion::AddObjectRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbdc6bafe38a479a9ULL;
  static const uint64_t static_value2 = 0xea4dff4f456ad1d5ULL;
};

template<class ContainerAllocator>
struct DataType< ::fetch_grasp_suggestion::AddObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fetch_grasp_suggestion/AddObjectRequest";
  }

  static const char* value(const ::fetch_grasp_suggestion::AddObjectRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fetch_grasp_suggestion::AddObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/PointCloud2[] point_clouds    # Segmented point cloud for each object\n"
"geometry_msgs/Point[] centroids           # Centroid of the point cloud for each object\n"
"int32[] indices                           # Index in the grasp selector object list for each object\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointCloud2\n"
"# This message holds a collection of N-dimensional points, which may\n"
"# contain additional information such as normals, intensity, etc. The\n"
"# point data is stored as a binary blob, its layout described by the\n"
"# contents of the \"fields\" array.\n"
"\n"
"# The point cloud data may be organized 2d (image-like) or 1d\n"
"# (unordered). Point clouds organized as 2d images may be produced by\n"
"# camera depth sensors such as stereo or time-of-flight.\n"
"\n"
"# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n"
"# points).\n"
"Header header\n"
"\n"
"# 2D structure of the point cloud. If the cloud is unordered, height is\n"
"# 1 and width is the length of the point cloud.\n"
"uint32 height\n"
"uint32 width\n"
"\n"
"# Describes the channels and their layout in the binary data blob.\n"
"PointField[] fields\n"
"\n"
"bool    is_bigendian # Is this data bigendian?\n"
"uint32  point_step   # Length of a point in bytes\n"
"uint32  row_step     # Length of a row in bytes\n"
"uint8[] data         # Actual point data, size is (row_step*height)\n"
"\n"
"bool is_dense        # True if there are no invalid points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointField\n"
"# This message holds the description of one point entry in the\n"
"# PointCloud2 message format.\n"
"uint8 INT8    = 1\n"
"uint8 UINT8   = 2\n"
"uint8 INT16   = 3\n"
"uint8 UINT16  = 4\n"
"uint8 INT32   = 5\n"
"uint8 UINT32  = 6\n"
"uint8 FLOAT32 = 7\n"
"uint8 FLOAT64 = 8\n"
"\n"
"string name      # Name of field\n"
"uint32 offset    # Offset from start of point struct\n"
"uint8  datatype  # Datatype enumeration, see above\n"
"uint32 count     # How many elements in the field\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::fetch_grasp_suggestion::AddObjectRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fetch_grasp_suggestion::AddObjectRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.point_clouds);
      stream.next(m.centroids);
      stream.next(m.indices);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddObjectRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fetch_grasp_suggestion::AddObjectRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fetch_grasp_suggestion::AddObjectRequest_<ContainerAllocator>& v)
  {
    s << indent << "point_clouds[]" << std::endl;
    for (size_t i = 0; i < v.point_clouds.size(); ++i)
    {
      s << indent << "  point_clouds[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "    ", v.point_clouds[i]);
    }
    s << indent << "centroids[]" << std::endl;
    for (size_t i = 0; i < v.centroids.size(); ++i)
    {
      s << indent << "  centroids[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.centroids[i]);
    }
    s << indent << "indices[]" << std::endl;
    for (size_t i = 0; i < v.indices.size(); ++i)
    {
      s << indent << "  indices[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.indices[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FETCH_GRASP_SUGGESTION_MESSAGE_ADDOBJECTREQUEST_H
