// Generated by gencpp from file fetch_grasp_suggestion/ClassifyGraspPair.msg
// DO NOT EDIT!


#ifndef FETCH_GRASP_SUGGESTION_MESSAGE_CLASSIFYGRASPPAIR_H
#define FETCH_GRASP_SUGGESTION_MESSAGE_CLASSIFYGRASPPAIR_H

#include <ros/service_traits.h>


#include <fetch_grasp_suggestion/ClassifyGraspPairRequest.h>
#include <fetch_grasp_suggestion/ClassifyGraspPairResponse.h>


namespace fetch_grasp_suggestion
{

struct ClassifyGraspPair
{

typedef ClassifyGraspPairRequest Request;
typedef ClassifyGraspPairResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ClassifyGraspPair
} // namespace fetch_grasp_suggestion


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fetch_grasp_suggestion::ClassifyGraspPair > {
  static const char* value()
  {
    return "a1df00a394ee949d030571f1d7eaac62";
  }

  static const char* value(const ::fetch_grasp_suggestion::ClassifyGraspPair&) { return value(); }
};

template<>
struct DataType< ::fetch_grasp_suggestion::ClassifyGraspPair > {
  static const char* value()
  {
    return "fetch_grasp_suggestion/ClassifyGraspPair";
  }

  static const char* value(const ::fetch_grasp_suggestion::ClassifyGraspPair&) { return value(); }
};


// service_traits::MD5Sum< ::fetch_grasp_suggestion::ClassifyGraspPairRequest> should match
// service_traits::MD5Sum< ::fetch_grasp_suggestion::ClassifyGraspPair >
template<>
struct MD5Sum< ::fetch_grasp_suggestion::ClassifyGraspPairRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fetch_grasp_suggestion::ClassifyGraspPair >::value();
  }
  static const char* value(const ::fetch_grasp_suggestion::ClassifyGraspPairRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fetch_grasp_suggestion::ClassifyGraspPairRequest> should match
// service_traits::DataType< ::fetch_grasp_suggestion::ClassifyGraspPair >
template<>
struct DataType< ::fetch_grasp_suggestion::ClassifyGraspPairRequest>
{
  static const char* value()
  {
    return DataType< ::fetch_grasp_suggestion::ClassifyGraspPair >::value();
  }
  static const char* value(const ::fetch_grasp_suggestion::ClassifyGraspPairRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fetch_grasp_suggestion::ClassifyGraspPairResponse> should match
// service_traits::MD5Sum< ::fetch_grasp_suggestion::ClassifyGraspPair >
template<>
struct MD5Sum< ::fetch_grasp_suggestion::ClassifyGraspPairResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fetch_grasp_suggestion::ClassifyGraspPair >::value();
  }
  static const char* value(const ::fetch_grasp_suggestion::ClassifyGraspPairResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fetch_grasp_suggestion::ClassifyGraspPairResponse> should match
// service_traits::DataType< ::fetch_grasp_suggestion::ClassifyGraspPair >
template<>
struct DataType< ::fetch_grasp_suggestion::ClassifyGraspPairResponse>
{
  static const char* value()
  {
    return DataType< ::fetch_grasp_suggestion::ClassifyGraspPair >::value();
  }
  static const char* value(const ::fetch_grasp_suggestion::ClassifyGraspPairResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FETCH_GRASP_SUGGESTION_MESSAGE_CLASSIFYGRASPPAIR_H
