// Generated by gencpp from file fetch_grasp_suggestion/CycleGraspsRequest.msg
// DO NOT EDIT!


#ifndef FETCH_GRASP_SUGGESTION_MESSAGE_CYCLEGRASPSREQUEST_H
#define FETCH_GRASP_SUGGESTION_MESSAGE_CYCLEGRASPSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fetch_grasp_suggestion
{
template <class ContainerAllocator>
struct CycleGraspsRequest_
{
  typedef CycleGraspsRequest_<ContainerAllocator> Type;

  CycleGraspsRequest_()
    : forward(false)  {
    }
  CycleGraspsRequest_(const ContainerAllocator& _alloc)
    : forward(false)  {
  (void)_alloc;
    }



   typedef uint8_t _forward_type;
  _forward_type forward;





  typedef boost::shared_ptr< ::fetch_grasp_suggestion::CycleGraspsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fetch_grasp_suggestion::CycleGraspsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CycleGraspsRequest_

typedef ::fetch_grasp_suggestion::CycleGraspsRequest_<std::allocator<void> > CycleGraspsRequest;

typedef boost::shared_ptr< ::fetch_grasp_suggestion::CycleGraspsRequest > CycleGraspsRequestPtr;
typedef boost::shared_ptr< ::fetch_grasp_suggestion::CycleGraspsRequest const> CycleGraspsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fetch_grasp_suggestion::CycleGraspsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fetch_grasp_suggestion::CycleGraspsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fetch_grasp_suggestion::CycleGraspsRequest_<ContainerAllocator1> & lhs, const ::fetch_grasp_suggestion::CycleGraspsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.forward == rhs.forward;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fetch_grasp_suggestion::CycleGraspsRequest_<ContainerAllocator1> & lhs, const ::fetch_grasp_suggestion::CycleGraspsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fetch_grasp_suggestion

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fetch_grasp_suggestion::CycleGraspsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fetch_grasp_suggestion::CycleGraspsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fetch_grasp_suggestion::CycleGraspsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fetch_grasp_suggestion::CycleGraspsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fetch_grasp_suggestion::CycleGraspsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fetch_grasp_suggestion::CycleGraspsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fetch_grasp_suggestion::CycleGraspsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0fc3bc45e28c68f06921185960eb727c";
  }

  static const char* value(const ::fetch_grasp_suggestion::CycleGraspsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0fc3bc45e28c68f0ULL;
  static const uint64_t static_value2 = 0x6921185960eb727cULL;
};

template<class ContainerAllocator>
struct DataType< ::fetch_grasp_suggestion::CycleGraspsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fetch_grasp_suggestion/CycleGraspsRequest";
  }

  static const char* value(const ::fetch_grasp_suggestion::CycleGraspsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fetch_grasp_suggestion::CycleGraspsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool forward\n"
;
  }

  static const char* value(const ::fetch_grasp_suggestion::CycleGraspsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fetch_grasp_suggestion::CycleGraspsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.forward);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CycleGraspsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fetch_grasp_suggestion::CycleGraspsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fetch_grasp_suggestion::CycleGraspsRequest_<ContainerAllocator>& v)
  {
    s << indent << "forward: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.forward);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FETCH_GRASP_SUGGESTION_MESSAGE_CYCLEGRASPSREQUEST_H
