// Generated by gencpp from file fetch_grasp_suggestion/CycleGraspsResponse.msg
// DO NOT EDIT!


#ifndef FETCH_GRASP_SUGGESTION_MESSAGE_CYCLEGRASPSRESPONSE_H
#define FETCH_GRASP_SUGGESTION_MESSAGE_CYCLEGRASPSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace fetch_grasp_suggestion
{
template <class ContainerAllocator>
struct CycleGraspsResponse_
{
  typedef CycleGraspsResponse_<ContainerAllocator> Type;

  CycleGraspsResponse_()
    : grasp()
    , index(0)  {
    }
  CycleGraspsResponse_(const ContainerAllocator& _alloc)
    : grasp(_alloc)
    , index(0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _grasp_type;
  _grasp_type grasp;

   typedef int16_t _index_type;
  _index_type index;





  typedef boost::shared_ptr< ::fetch_grasp_suggestion::CycleGraspsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fetch_grasp_suggestion::CycleGraspsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CycleGraspsResponse_

typedef ::fetch_grasp_suggestion::CycleGraspsResponse_<std::allocator<void> > CycleGraspsResponse;

typedef boost::shared_ptr< ::fetch_grasp_suggestion::CycleGraspsResponse > CycleGraspsResponsePtr;
typedef boost::shared_ptr< ::fetch_grasp_suggestion::CycleGraspsResponse const> CycleGraspsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fetch_grasp_suggestion::CycleGraspsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fetch_grasp_suggestion::CycleGraspsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fetch_grasp_suggestion::CycleGraspsResponse_<ContainerAllocator1> & lhs, const ::fetch_grasp_suggestion::CycleGraspsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.grasp == rhs.grasp &&
    lhs.index == rhs.index;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fetch_grasp_suggestion::CycleGraspsResponse_<ContainerAllocator1> & lhs, const ::fetch_grasp_suggestion::CycleGraspsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fetch_grasp_suggestion

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fetch_grasp_suggestion::CycleGraspsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fetch_grasp_suggestion::CycleGraspsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fetch_grasp_suggestion::CycleGraspsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fetch_grasp_suggestion::CycleGraspsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fetch_grasp_suggestion::CycleGraspsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fetch_grasp_suggestion::CycleGraspsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fetch_grasp_suggestion::CycleGraspsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "82ee01379d9abc428bbc4f75a7f27bf7";
  }

  static const char* value(const ::fetch_grasp_suggestion::CycleGraspsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x82ee01379d9abc42ULL;
  static const uint64_t static_value2 = 0x8bbc4f75a7f27bf7ULL;
};

template<class ContainerAllocator>
struct DataType< ::fetch_grasp_suggestion::CycleGraspsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fetch_grasp_suggestion/CycleGraspsResponse";
  }

  static const char* value(const ::fetch_grasp_suggestion::CycleGraspsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fetch_grasp_suggestion::CycleGraspsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseStamped grasp\n"
"int16 index\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::fetch_grasp_suggestion::CycleGraspsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fetch_grasp_suggestion::CycleGraspsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.grasp);
      stream.next(m.index);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CycleGraspsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fetch_grasp_suggestion::CycleGraspsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fetch_grasp_suggestion::CycleGraspsResponse_<ContainerAllocator>& v)
  {
    s << indent << "grasp: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.grasp);
    s << indent << "index: ";
    Printer<int16_t>::stream(s, indent + "  ", v.index);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FETCH_GRASP_SUGGESTION_MESSAGE_CYCLEGRASPSRESPONSE_H
