// Generated by gencpp from file fetch_grasp_suggestion/ExecuteSelectedGraspAction.msg
// DO NOT EDIT!


#ifndef FETCH_GRASP_SUGGESTION_MESSAGE_EXECUTESELECTEDGRASPACTION_H
#define FETCH_GRASP_SUGGESTION_MESSAGE_EXECUTESELECTEDGRASPACTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <fetch_grasp_suggestion/ExecuteSelectedGraspActionGoal.h>
#include <fetch_grasp_suggestion/ExecuteSelectedGraspActionResult.h>
#include <fetch_grasp_suggestion/ExecuteSelectedGraspActionFeedback.h>

namespace fetch_grasp_suggestion
{
template <class ContainerAllocator>
struct ExecuteSelectedGraspAction_
{
  typedef ExecuteSelectedGraspAction_<ContainerAllocator> Type;

  ExecuteSelectedGraspAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  ExecuteSelectedGraspAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::fetch_grasp_suggestion::ExecuteSelectedGraspActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::fetch_grasp_suggestion::ExecuteSelectedGraspActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::fetch_grasp_suggestion::ExecuteSelectedGraspActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::fetch_grasp_suggestion::ExecuteSelectedGraspAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fetch_grasp_suggestion::ExecuteSelectedGraspAction_<ContainerAllocator> const> ConstPtr;

}; // struct ExecuteSelectedGraspAction_

typedef ::fetch_grasp_suggestion::ExecuteSelectedGraspAction_<std::allocator<void> > ExecuteSelectedGraspAction;

typedef boost::shared_ptr< ::fetch_grasp_suggestion::ExecuteSelectedGraspAction > ExecuteSelectedGraspActionPtr;
typedef boost::shared_ptr< ::fetch_grasp_suggestion::ExecuteSelectedGraspAction const> ExecuteSelectedGraspActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fetch_grasp_suggestion::ExecuteSelectedGraspAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fetch_grasp_suggestion::ExecuteSelectedGraspAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fetch_grasp_suggestion::ExecuteSelectedGraspAction_<ContainerAllocator1> & lhs, const ::fetch_grasp_suggestion::ExecuteSelectedGraspAction_<ContainerAllocator2> & rhs)
{
  return lhs.action_goal == rhs.action_goal &&
    lhs.action_result == rhs.action_result &&
    lhs.action_feedback == rhs.action_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fetch_grasp_suggestion::ExecuteSelectedGraspAction_<ContainerAllocator1> & lhs, const ::fetch_grasp_suggestion::ExecuteSelectedGraspAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fetch_grasp_suggestion

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fetch_grasp_suggestion::ExecuteSelectedGraspAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fetch_grasp_suggestion::ExecuteSelectedGraspAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fetch_grasp_suggestion::ExecuteSelectedGraspAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fetch_grasp_suggestion::ExecuteSelectedGraspAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fetch_grasp_suggestion::ExecuteSelectedGraspAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fetch_grasp_suggestion::ExecuteSelectedGraspAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fetch_grasp_suggestion::ExecuteSelectedGraspAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bb693185d169fd1638ff40cfe9c85ee9";
  }

  static const char* value(const ::fetch_grasp_suggestion::ExecuteSelectedGraspAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbb693185d169fd16ULL;
  static const uint64_t static_value2 = 0x38ff40cfe9c85ee9ULL;
};

template<class ContainerAllocator>
struct DataType< ::fetch_grasp_suggestion::ExecuteSelectedGraspAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fetch_grasp_suggestion/ExecuteSelectedGraspAction";
  }

  static const char* value(const ::fetch_grasp_suggestion::ExecuteSelectedGraspAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fetch_grasp_suggestion::ExecuteSelectedGraspAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"ExecuteSelectedGraspActionGoal action_goal\n"
"ExecuteSelectedGraspActionResult action_result\n"
"ExecuteSelectedGraspActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: fetch_grasp_suggestion/ExecuteSelectedGraspActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"ExecuteSelectedGraspGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: fetch_grasp_suggestion/ExecuteSelectedGraspGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"================================================================================\n"
"MSG: fetch_grasp_suggestion/ExecuteSelectedGraspActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"ExecuteSelectedGraspResult result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: fetch_grasp_suggestion/ExecuteSelectedGraspResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"int32 APPROACH=-1                     # Failure to plan or move to approach pose\n"
"int32 GRASP_PLAN=-2                   # Failure to plan from approach pose to grasp pose\n"
"int32 GRASP_EXECUTION=-3              # Failure to execute trajectory to grasp pose\n"
"int32 PICK_UP_PLAN=-4                 # Failure to plan to pick up pose\n"
"int32 PICK_UP_EXECUTION=-5            # Failure to execute trajectory to pick up pose\n"
"\n"
"bool success                          # True if the object is verified to be in the gripper after pickup\n"
"int32 error_code                       # MoveIt error code (as defined in moveit_msgs/MoveItErrorCodes.msg)\n"
"int32 failure_point                    # What stage of the action failed\n"
"\n"
"================================================================================\n"
"MSG: fetch_grasp_suggestion/ExecuteSelectedGraspActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"ExecuteSelectedGraspFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: fetch_grasp_suggestion/ExecuteSelectedGraspFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"string message                        # The current state message\n"
;
  }

  static const char* value(const ::fetch_grasp_suggestion::ExecuteSelectedGraspAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fetch_grasp_suggestion::ExecuteSelectedGraspAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecuteSelectedGraspAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fetch_grasp_suggestion::ExecuteSelectedGraspAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fetch_grasp_suggestion::ExecuteSelectedGraspAction_<ContainerAllocator>& v)
  {
    s << indent << "action_goal: ";
    s << std::endl;
    Printer< ::fetch_grasp_suggestion::ExecuteSelectedGraspActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
    s << std::endl;
    Printer< ::fetch_grasp_suggestion::ExecuteSelectedGraspActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
    s << std::endl;
    Printer< ::fetch_grasp_suggestion::ExecuteSelectedGraspActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FETCH_GRASP_SUGGESTION_MESSAGE_EXECUTESELECTEDGRASPACTION_H
