// Generated by gencpp from file fetch_grasp_suggestion/PairwiseRankRequest.msg
// DO NOT EDIT!


#ifndef FETCH_GRASP_SUGGESTION_MESSAGE_PAIRWISERANKREQUEST_H
#define FETCH_GRASP_SUGGESTION_MESSAGE_PAIRWISERANKREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fetch_grasp_suggestion
{
template <class ContainerAllocator>
struct PairwiseRankRequest_
{
  typedef PairwiseRankRequest_<ContainerAllocator> Type;

  PairwiseRankRequest_()
    {
    }
  PairwiseRankRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::fetch_grasp_suggestion::PairwiseRankRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fetch_grasp_suggestion::PairwiseRankRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PairwiseRankRequest_

typedef ::fetch_grasp_suggestion::PairwiseRankRequest_<std::allocator<void> > PairwiseRankRequest;

typedef boost::shared_ptr< ::fetch_grasp_suggestion::PairwiseRankRequest > PairwiseRankRequestPtr;
typedef boost::shared_ptr< ::fetch_grasp_suggestion::PairwiseRankRequest const> PairwiseRankRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fetch_grasp_suggestion::PairwiseRankRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fetch_grasp_suggestion::PairwiseRankRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace fetch_grasp_suggestion

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fetch_grasp_suggestion::PairwiseRankRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fetch_grasp_suggestion::PairwiseRankRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fetch_grasp_suggestion::PairwiseRankRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fetch_grasp_suggestion::PairwiseRankRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fetch_grasp_suggestion::PairwiseRankRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fetch_grasp_suggestion::PairwiseRankRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fetch_grasp_suggestion::PairwiseRankRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::fetch_grasp_suggestion::PairwiseRankRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::fetch_grasp_suggestion::PairwiseRankRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fetch_grasp_suggestion/PairwiseRankRequest";
  }

  static const char* value(const ::fetch_grasp_suggestion::PairwiseRankRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fetch_grasp_suggestion::PairwiseRankRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::fetch_grasp_suggestion::PairwiseRankRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fetch_grasp_suggestion::PairwiseRankRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PairwiseRankRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fetch_grasp_suggestion::PairwiseRankRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::fetch_grasp_suggestion::PairwiseRankRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // FETCH_GRASP_SUGGESTION_MESSAGE_PAIRWISERANKREQUEST_H
