// Generated by gencpp from file fetch_grasp_suggestion/PresetMoveFeedback.msg
// DO NOT EDIT!


#ifndef FETCH_GRASP_SUGGESTION_MESSAGE_PRESETMOVEFEEDBACK_H
#define FETCH_GRASP_SUGGESTION_MESSAGE_PRESETMOVEFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fetch_grasp_suggestion
{
template <class ContainerAllocator>
struct PresetMoveFeedback_
{
  typedef PresetMoveFeedback_<ContainerAllocator> Type;

  PresetMoveFeedback_()
    {
    }
  PresetMoveFeedback_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::fetch_grasp_suggestion::PresetMoveFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fetch_grasp_suggestion::PresetMoveFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct PresetMoveFeedback_

typedef ::fetch_grasp_suggestion::PresetMoveFeedback_<std::allocator<void> > PresetMoveFeedback;

typedef boost::shared_ptr< ::fetch_grasp_suggestion::PresetMoveFeedback > PresetMoveFeedbackPtr;
typedef boost::shared_ptr< ::fetch_grasp_suggestion::PresetMoveFeedback const> PresetMoveFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fetch_grasp_suggestion::PresetMoveFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fetch_grasp_suggestion::PresetMoveFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace fetch_grasp_suggestion

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fetch_grasp_suggestion::PresetMoveFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fetch_grasp_suggestion::PresetMoveFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fetch_grasp_suggestion::PresetMoveFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fetch_grasp_suggestion::PresetMoveFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fetch_grasp_suggestion::PresetMoveFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fetch_grasp_suggestion::PresetMoveFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fetch_grasp_suggestion::PresetMoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::fetch_grasp_suggestion::PresetMoveFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::fetch_grasp_suggestion::PresetMoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fetch_grasp_suggestion/PresetMoveFeedback";
  }

  static const char* value(const ::fetch_grasp_suggestion::PresetMoveFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fetch_grasp_suggestion::PresetMoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
;
  }

  static const char* value(const ::fetch_grasp_suggestion::PresetMoveFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fetch_grasp_suggestion::PresetMoveFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PresetMoveFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fetch_grasp_suggestion::PresetMoveFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::fetch_grasp_suggestion::PresetMoveFeedback_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // FETCH_GRASP_SUGGESTION_MESSAGE_PRESETMOVEFEEDBACK_H
