(cl:defpackage segmentation-srv
  (:use )
  (:export
   "OBJECT_DETECTION"
   "<OBJECT_DETECTION-REQUEST>"
   "OBJECT_DETECTION-REQUEST"
   "<OBJECT_DETECTION-RESPONSE>"
   "OBJECT_DETECTION-RESPONSE"
   "STRETCHSEGMENTATION"
   "<STRETCHSEGMENTATION-REQUEST>"
   "STRETCHSEGMENTATION-REQUEST"
   "<STRETCHSEGMENTATION-RESPONSE>"
   "STRETCHSEGMENTATION-RESPONSE"
  ))

