(cl:defpackage stretch_fetch_grasp_bridge-srv
  (:use )
  (:export
   "STRETCHGRASPPOSE"
   "<STRETCHGRASPPOSE-REQUEST>"
   "STRETCHGRASPPOSE-REQUEST"
   "<STRETCHGRASPPOSE-RESPONSE>"
   "STRETCHGRASPPOSE-RESPONSE"
   "STRETCHGRASPPOSEV2"
   "<STRETCHGRASPPOSEV2-REQUEST>"
   "STRETCHGRASPPOSEV2-REQUEST"
   "<STRETCHGRASPPOSEV2-RESPONSE>"
   "STRETCHGRASPPOSEV2-RESPONSE"
   "STRETCHSEGMENTATION"
   "<STRETCHSEGMENTATION-REQUEST>"
   "STRETCHSEGMENTATION-REQUEST"
   "<STRETCHSEGMENTATION-RESPONSE>"
   "STRETCHSEGMENTATION-RESPONSE"
  ))

