# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rail_grasp_calculation_msgs/RankGraspsGoal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import rail_grasp_calculation_msgs.msg
import sensor_msgs.msg
import std_msgs.msg

class RankGraspsGoal(genpy.Message):
  _md5sum = "0e590bb1f43077b5b1f047d5b255cf91"
  _type = "rail_grasp_calculation_msgs/RankGraspsGoal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# Define the goal

# Required: list of sampled grasps, to be clustered and ranked
geometry_msgs/PoseArray graspList

# Required: complete point cloud of the environment
sensor_msgs/PointCloud2 sceneCloud

# Optional: segmented point cloud of an object of interest; required for object-based grasp ranking
sensor_msgs/PointCloud2 segmentedCloud

# Optional: workspace for grasp calculation; required for point-of-interest grasp ranking
rail_grasp_calculation_msgs/Workspace workspace         # Note: this is defined in the frame of the sceneCloud


================================================================================
MSG: geometry_msgs/PoseArray
# An array of poses with a header for global reference.

Header header

Pose[] poses

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: sensor_msgs/PointCloud2
# This message holds a collection of N-dimensional points, which may
# contain additional information such as normals, intensity, etc. The
# point data is stored as a binary blob, its layout described by the
# contents of the "fields" array.

# The point cloud data may be organized 2d (image-like) or 1d
# (unordered). Point clouds organized as 2d images may be produced by
# camera depth sensors such as stereo or time-of-flight.

# Time of sensor data acquisition, and the coordinate frame ID (for 3d
# points).
Header header

# 2D structure of the point cloud. If the cloud is unordered, height is
# 1 and width is the length of the point cloud.
uint32 height
uint32 width

# Describes the channels and their layout in the binary data blob.
PointField[] fields

bool    is_bigendian # Is this data bigendian?
uint32  point_step   # Length of a point in bytes
uint32  row_step     # Length of a row in bytes
uint8[] data         # Actual point data, size is (row_step*height)

bool is_dense        # True if there are no invalid points

================================================================================
MSG: sensor_msgs/PointField
# This message holds the description of one point entry in the
# PointCloud2 message format.
uint8 INT8    = 1
uint8 UINT8   = 2
uint8 INT16   = 3
uint8 UINT16  = 4
uint8 INT32   = 5
uint8 UINT32  = 6
uint8 FLOAT32 = 7
uint8 FLOAT64 = 8

string name      # Name of field
uint32 offset    # Offset from start of point struct
uint8  datatype  # Datatype enumeration, see above
uint32 count     # How many elements in the field

================================================================================
MSG: rail_grasp_calculation_msgs/Workspace
uint8 WORKSPACE_VOLUME = 0
uint8 CENTERED_ROI = 1

uint8 mode                              # workspace definition mode, either WORKSPACE_VOLUME or CENTERED_ROI
float64 x_min                           # minimum x bound of rectangular workspace (for WORKSPACE_VOLUME only)
float64 x_max                           # maximum x bound of rectangular workspace (for WORKSPACE_VOLUME only)
float64 y_min                           # minimum y bound of rectangular workspace (for WORKSPACE_VOLUME only)
float64 y_max                           # maximum y bound of rectangular workspace (for WORKSPACE_VOLUME only)
float64 z_min                           # minimum z bound of rectangular workspace (for WORKSPACE_VOLUME only)
float64 z_max                           # maximum z bound of rectangular workspace (for WORKSPACE_VOLUME only)
geometry_msgs/Point roiCenter           # workspace center point (for CENTERED_ROI only)
geometry_msgs/Vector3 roiDimensions     # workspace bounds (for CENTERED_ROI only)
================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['graspList','sceneCloud','segmentedCloud','workspace']
  _slot_types = ['geometry_msgs/PoseArray','sensor_msgs/PointCloud2','sensor_msgs/PointCloud2','rail_grasp_calculation_msgs/Workspace']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       graspList,sceneCloud,segmentedCloud,workspace

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RankGraspsGoal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.graspList is None:
        self.graspList = geometry_msgs.msg.PoseArray()
      if self.sceneCloud is None:
        self.sceneCloud = sensor_msgs.msg.PointCloud2()
      if self.segmentedCloud is None:
        self.segmentedCloud = sensor_msgs.msg.PointCloud2()
      if self.workspace is None:
        self.workspace = rail_grasp_calculation_msgs.msg.Workspace()
    else:
      self.graspList = geometry_msgs.msg.PoseArray()
      self.sceneCloud = sensor_msgs.msg.PointCloud2()
      self.segmentedCloud = sensor_msgs.msg.PointCloud2()
      self.workspace = rail_grasp_calculation_msgs.msg.Workspace()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.graspList.header.seq, _x.graspList.header.stamp.secs, _x.graspList.header.stamp.nsecs))
      _x = self.graspList.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.graspList.poses)
      buff.write(_struct_I.pack(length))
      for val1 in self.graspList.poses:
        _v1 = val1.position
        _x = _v1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v2 = val1.orientation
        _x = _v2
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
      _x = self
      buff.write(_get_struct_3I().pack(_x.sceneCloud.header.seq, _x.sceneCloud.header.stamp.secs, _x.sceneCloud.header.stamp.nsecs))
      _x = self.sceneCloud.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.sceneCloud.height, _x.sceneCloud.width))
      length = len(self.sceneCloud.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.sceneCloud.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.sceneCloud.is_bigendian, _x.sceneCloud.point_step, _x.sceneCloud.row_step))
      _x = self.sceneCloud.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B3I().pack(_x.sceneCloud.is_dense, _x.segmentedCloud.header.seq, _x.segmentedCloud.header.stamp.secs, _x.segmentedCloud.header.stamp.nsecs))
      _x = self.segmentedCloud.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.segmentedCloud.height, _x.segmentedCloud.width))
      length = len(self.segmentedCloud.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.segmentedCloud.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.segmentedCloud.is_bigendian, _x.segmentedCloud.point_step, _x.segmentedCloud.row_step))
      _x = self.segmentedCloud.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2B12d().pack(_x.segmentedCloud.is_dense, _x.workspace.mode, _x.workspace.x_min, _x.workspace.x_max, _x.workspace.y_min, _x.workspace.y_max, _x.workspace.z_min, _x.workspace.z_max, _x.workspace.roiCenter.x, _x.workspace.roiCenter.y, _x.workspace.roiCenter.z, _x.workspace.roiDimensions.x, _x.workspace.roiDimensions.y, _x.workspace.roiDimensions.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.graspList is None:
        self.graspList = geometry_msgs.msg.PoseArray()
      if self.sceneCloud is None:
        self.sceneCloud = sensor_msgs.msg.PointCloud2()
      if self.segmentedCloud is None:
        self.segmentedCloud = sensor_msgs.msg.PointCloud2()
      if self.workspace is None:
        self.workspace = rail_grasp_calculation_msgs.msg.Workspace()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.graspList.header.seq, _x.graspList.header.stamp.secs, _x.graspList.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.graspList.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.graspList.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.graspList.poses = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Pose()
        _v3 = val1.position
        _x = _v3
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v4 = val1.orientation
        _x = _v4
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        self.graspList.poses.append(val1)
      _x = self
      start = end
      end += 12
      (_x.sceneCloud.header.seq, _x.sceneCloud.header.stamp.secs, _x.sceneCloud.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.sceneCloud.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.sceneCloud.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.sceneCloud.height, _x.sceneCloud.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.sceneCloud.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
        self.sceneCloud.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.sceneCloud.is_bigendian, _x.sceneCloud.point_step, _x.sceneCloud.row_step,) = _get_struct_B2I().unpack(str[start:end])
      self.sceneCloud.is_bigendian = bool(self.sceneCloud.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.sceneCloud.data = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.sceneCloud.is_dense, _x.segmentedCloud.header.seq, _x.segmentedCloud.header.stamp.secs, _x.segmentedCloud.header.stamp.nsecs,) = _get_struct_B3I().unpack(str[start:end])
      self.sceneCloud.is_dense = bool(self.sceneCloud.is_dense)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.segmentedCloud.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.segmentedCloud.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.segmentedCloud.height, _x.segmentedCloud.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.segmentedCloud.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
        self.segmentedCloud.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.segmentedCloud.is_bigendian, _x.segmentedCloud.point_step, _x.segmentedCloud.row_step,) = _get_struct_B2I().unpack(str[start:end])
      self.segmentedCloud.is_bigendian = bool(self.segmentedCloud.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.segmentedCloud.data = str[start:end]
      _x = self
      start = end
      end += 98
      (_x.segmentedCloud.is_dense, _x.workspace.mode, _x.workspace.x_min, _x.workspace.x_max, _x.workspace.y_min, _x.workspace.y_max, _x.workspace.z_min, _x.workspace.z_max, _x.workspace.roiCenter.x, _x.workspace.roiCenter.y, _x.workspace.roiCenter.z, _x.workspace.roiDimensions.x, _x.workspace.roiDimensions.y, _x.workspace.roiDimensions.z,) = _get_struct_2B12d().unpack(str[start:end])
      self.segmentedCloud.is_dense = bool(self.segmentedCloud.is_dense)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.graspList.header.seq, _x.graspList.header.stamp.secs, _x.graspList.header.stamp.nsecs))
      _x = self.graspList.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.graspList.poses)
      buff.write(_struct_I.pack(length))
      for val1 in self.graspList.poses:
        _v5 = val1.position
        _x = _v5
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v6 = val1.orientation
        _x = _v6
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
      _x = self
      buff.write(_get_struct_3I().pack(_x.sceneCloud.header.seq, _x.sceneCloud.header.stamp.secs, _x.sceneCloud.header.stamp.nsecs))
      _x = self.sceneCloud.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.sceneCloud.height, _x.sceneCloud.width))
      length = len(self.sceneCloud.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.sceneCloud.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.sceneCloud.is_bigendian, _x.sceneCloud.point_step, _x.sceneCloud.row_step))
      _x = self.sceneCloud.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B3I().pack(_x.sceneCloud.is_dense, _x.segmentedCloud.header.seq, _x.segmentedCloud.header.stamp.secs, _x.segmentedCloud.header.stamp.nsecs))
      _x = self.segmentedCloud.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.segmentedCloud.height, _x.segmentedCloud.width))
      length = len(self.segmentedCloud.fields)
      buff.write(_struct_I.pack(length))
      for val1 in self.segmentedCloud.fields:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_IBI().pack(_x.offset, _x.datatype, _x.count))
      _x = self
      buff.write(_get_struct_B2I().pack(_x.segmentedCloud.is_bigendian, _x.segmentedCloud.point_step, _x.segmentedCloud.row_step))
      _x = self.segmentedCloud.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2B12d().pack(_x.segmentedCloud.is_dense, _x.workspace.mode, _x.workspace.x_min, _x.workspace.x_max, _x.workspace.y_min, _x.workspace.y_max, _x.workspace.z_min, _x.workspace.z_max, _x.workspace.roiCenter.x, _x.workspace.roiCenter.y, _x.workspace.roiCenter.z, _x.workspace.roiDimensions.x, _x.workspace.roiDimensions.y, _x.workspace.roiDimensions.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.graspList is None:
        self.graspList = geometry_msgs.msg.PoseArray()
      if self.sceneCloud is None:
        self.sceneCloud = sensor_msgs.msg.PointCloud2()
      if self.segmentedCloud is None:
        self.segmentedCloud = sensor_msgs.msg.PointCloud2()
      if self.workspace is None:
        self.workspace = rail_grasp_calculation_msgs.msg.Workspace()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.graspList.header.seq, _x.graspList.header.stamp.secs, _x.graspList.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.graspList.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.graspList.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.graspList.poses = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Pose()
        _v7 = val1.position
        _x = _v7
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v8 = val1.orientation
        _x = _v8
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        self.graspList.poses.append(val1)
      _x = self
      start = end
      end += 12
      (_x.sceneCloud.header.seq, _x.sceneCloud.header.stamp.secs, _x.sceneCloud.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.sceneCloud.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.sceneCloud.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.sceneCloud.height, _x.sceneCloud.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.sceneCloud.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
        self.sceneCloud.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.sceneCloud.is_bigendian, _x.sceneCloud.point_step, _x.sceneCloud.row_step,) = _get_struct_B2I().unpack(str[start:end])
      self.sceneCloud.is_bigendian = bool(self.sceneCloud.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.sceneCloud.data = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.sceneCloud.is_dense, _x.segmentedCloud.header.seq, _x.segmentedCloud.header.stamp.secs, _x.segmentedCloud.header.stamp.nsecs,) = _get_struct_B3I().unpack(str[start:end])
      self.sceneCloud.is_dense = bool(self.sceneCloud.is_dense)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.segmentedCloud.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.segmentedCloud.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.segmentedCloud.height, _x.segmentedCloud.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.segmentedCloud.fields = []
      for i in range(0, length):
        val1 = sensor_msgs.msg.PointField()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.name = str[start:end]
        _x = val1
        start = end
        end += 9
        (_x.offset, _x.datatype, _x.count,) = _get_struct_IBI().unpack(str[start:end])
        self.segmentedCloud.fields.append(val1)
      _x = self
      start = end
      end += 9
      (_x.segmentedCloud.is_bigendian, _x.segmentedCloud.point_step, _x.segmentedCloud.row_step,) = _get_struct_B2I().unpack(str[start:end])
      self.segmentedCloud.is_bigendian = bool(self.segmentedCloud.is_bigendian)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.segmentedCloud.data = str[start:end]
      _x = self
      start = end
      end += 98
      (_x.segmentedCloud.is_dense, _x.workspace.mode, _x.workspace.x_min, _x.workspace.x_max, _x.workspace.y_min, _x.workspace.y_max, _x.workspace.z_min, _x.workspace.z_max, _x.workspace.roiCenter.x, _x.workspace.roiCenter.y, _x.workspace.roiCenter.z, _x.workspace.roiDimensions.x, _x.workspace.roiDimensions.y, _x.workspace.roiDimensions.z,) = _get_struct_2B12d().unpack(str[start:end])
      self.segmentedCloud.is_dense = bool(self.segmentedCloud.is_dense)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B12d = None
def _get_struct_2B12d():
    global _struct_2B12d
    if _struct_2B12d is None:
        _struct_2B12d = struct.Struct("<2B12d")
    return _struct_2B12d
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
_struct_B2I = None
def _get_struct_B2I():
    global _struct_B2I
    if _struct_B2I is None:
        _struct_B2I = struct.Struct("<B2I")
    return _struct_B2I
_struct_B3I = None
def _get_struct_B3I():
    global _struct_B3I
    if _struct_B3I is None:
        _struct_B3I = struct.Struct("<B3I")
    return _struct_B3I
_struct_IBI = None
def _get_struct_IBI():
    global _struct_IBI
    if _struct_IBI is None:
        _struct_IBI = struct.Struct("<IBI")
    return _struct_IBI
