# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rail_grasp_calculation_msgs/Workspace.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class Workspace(genpy.Message):
  _md5sum = "6d17931a043d8ef6982d0812ce82ff50"
  _type = "rail_grasp_calculation_msgs/Workspace"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 WORKSPACE_VOLUME = 0
uint8 CENTERED_ROI = 1

uint8 mode                              # workspace definition mode, either WORKSPACE_VOLUME or CENTERED_ROI
float64 x_min                           # minimum x bound of rectangular workspace (for WORKSPACE_VOLUME only)
float64 x_max                           # maximum x bound of rectangular workspace (for WORKSPACE_VOLUME only)
float64 y_min                           # minimum y bound of rectangular workspace (for WORKSPACE_VOLUME only)
float64 y_max                           # maximum y bound of rectangular workspace (for WORKSPACE_VOLUME only)
float64 z_min                           # minimum z bound of rectangular workspace (for WORKSPACE_VOLUME only)
float64 z_max                           # maximum z bound of rectangular workspace (for WORKSPACE_VOLUME only)
geometry_msgs/Point roiCenter           # workspace center point (for CENTERED_ROI only)
geometry_msgs/Vector3 roiDimensions     # workspace bounds (for CENTERED_ROI only)
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  # Pseudo-constants
  WORKSPACE_VOLUME = 0
  CENTERED_ROI = 1

  __slots__ = ['mode','x_min','x_max','y_min','y_max','z_min','z_max','roiCenter','roiDimensions']
  _slot_types = ['uint8','float64','float64','float64','float64','float64','float64','geometry_msgs/Point','geometry_msgs/Vector3']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       mode,x_min,x_max,y_min,y_max,z_min,z_max,roiCenter,roiDimensions

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Workspace, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.mode is None:
        self.mode = 0
      if self.x_min is None:
        self.x_min = 0.
      if self.x_max is None:
        self.x_max = 0.
      if self.y_min is None:
        self.y_min = 0.
      if self.y_max is None:
        self.y_max = 0.
      if self.z_min is None:
        self.z_min = 0.
      if self.z_max is None:
        self.z_max = 0.
      if self.roiCenter is None:
        self.roiCenter = geometry_msgs.msg.Point()
      if self.roiDimensions is None:
        self.roiDimensions = geometry_msgs.msg.Vector3()
    else:
      self.mode = 0
      self.x_min = 0.
      self.x_max = 0.
      self.y_min = 0.
      self.y_max = 0.
      self.z_min = 0.
      self.z_max = 0.
      self.roiCenter = geometry_msgs.msg.Point()
      self.roiDimensions = geometry_msgs.msg.Vector3()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B12d().pack(_x.mode, _x.x_min, _x.x_max, _x.y_min, _x.y_max, _x.z_min, _x.z_max, _x.roiCenter.x, _x.roiCenter.y, _x.roiCenter.z, _x.roiDimensions.x, _x.roiDimensions.y, _x.roiDimensions.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.roiCenter is None:
        self.roiCenter = geometry_msgs.msg.Point()
      if self.roiDimensions is None:
        self.roiDimensions = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 97
      (_x.mode, _x.x_min, _x.x_max, _x.y_min, _x.y_max, _x.z_min, _x.z_max, _x.roiCenter.x, _x.roiCenter.y, _x.roiCenter.z, _x.roiDimensions.x, _x.roiDimensions.y, _x.roiDimensions.z,) = _get_struct_B12d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B12d().pack(_x.mode, _x.x_min, _x.x_max, _x.y_min, _x.y_max, _x.z_min, _x.z_max, _x.roiCenter.x, _x.roiCenter.y, _x.roiCenter.z, _x.roiDimensions.x, _x.roiDimensions.y, _x.roiDimensions.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.roiCenter is None:
        self.roiCenter = geometry_msgs.msg.Point()
      if self.roiDimensions is None:
        self.roiDimensions = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 97
      (_x.mode, _x.x_min, _x.x_max, _x.y_min, _x.y_max, _x.z_min, _x.z_max, _x.roiCenter.x, _x.roiCenter.y, _x.roiCenter.z, _x.roiDimensions.x, _x.roiDimensions.y, _x.roiDimensions.z,) = _get_struct_B12d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B12d = None
def _get_struct_B12d():
    global _struct_B12d
    if _struct_B12d is None:
        _struct_B12d = struct.Struct("<B12d")
    return _struct_B12d
