// Generated by gencpp from file stretch_fetch_grasp_bridge/StretchGraspPose.msg
// DO NOT EDIT!


#ifndef STRETCH_FETCH_GRASP_BRIDGE_MESSAGE_STRETCHGRASPPOSE_H
#define STRETCH_FETCH_GRASP_BRIDGE_MESSAGE_STRETCHGRASPPOSE_H

#include <ros/service_traits.h>


#include <stretch_fetch_grasp_bridge/StretchGraspPoseRequest.h>
#include <stretch_fetch_grasp_bridge/StretchGraspPoseResponse.h>


namespace stretch_fetch_grasp_bridge
{

struct StretchGraspPose
{

typedef StretchGraspPoseRequest Request;
typedef StretchGraspPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StretchGraspPose
} // namespace stretch_fetch_grasp_bridge


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::stretch_fetch_grasp_bridge::StretchGraspPose > {
  static const char* value()
  {
    return "f2a5bd3eeea5099d248b5daddbc9ecef";
  }

  static const char* value(const ::stretch_fetch_grasp_bridge::StretchGraspPose&) { return value(); }
};

template<>
struct DataType< ::stretch_fetch_grasp_bridge::StretchGraspPose > {
  static const char* value()
  {
    return "stretch_fetch_grasp_bridge/StretchGraspPose";
  }

  static const char* value(const ::stretch_fetch_grasp_bridge::StretchGraspPose&) { return value(); }
};


// service_traits::MD5Sum< ::stretch_fetch_grasp_bridge::StretchGraspPoseRequest> should match
// service_traits::MD5Sum< ::stretch_fetch_grasp_bridge::StretchGraspPose >
template<>
struct MD5Sum< ::stretch_fetch_grasp_bridge::StretchGraspPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::stretch_fetch_grasp_bridge::StretchGraspPose >::value();
  }
  static const char* value(const ::stretch_fetch_grasp_bridge::StretchGraspPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::stretch_fetch_grasp_bridge::StretchGraspPoseRequest> should match
// service_traits::DataType< ::stretch_fetch_grasp_bridge::StretchGraspPose >
template<>
struct DataType< ::stretch_fetch_grasp_bridge::StretchGraspPoseRequest>
{
  static const char* value()
  {
    return DataType< ::stretch_fetch_grasp_bridge::StretchGraspPose >::value();
  }
  static const char* value(const ::stretch_fetch_grasp_bridge::StretchGraspPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::stretch_fetch_grasp_bridge::StretchGraspPoseResponse> should match
// service_traits::MD5Sum< ::stretch_fetch_grasp_bridge::StretchGraspPose >
template<>
struct MD5Sum< ::stretch_fetch_grasp_bridge::StretchGraspPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::stretch_fetch_grasp_bridge::StretchGraspPose >::value();
  }
  static const char* value(const ::stretch_fetch_grasp_bridge::StretchGraspPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::stretch_fetch_grasp_bridge::StretchGraspPoseResponse> should match
// service_traits::DataType< ::stretch_fetch_grasp_bridge::StretchGraspPose >
template<>
struct DataType< ::stretch_fetch_grasp_bridge::StretchGraspPoseResponse>
{
  static const char* value()
  {
    return DataType< ::stretch_fetch_grasp_bridge::StretchGraspPose >::value();
  }
  static const char* value(const ::stretch_fetch_grasp_bridge::StretchGraspPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STRETCH_FETCH_GRASP_BRIDGE_MESSAGE_STRETCHGRASPPOSE_H
