// Generated by gencpp from file segmentation/Object_detectionRequest.msg
// DO NOT EDIT!


#ifndef SEGMENTATION_MESSAGE_OBJECT_DETECTIONREQUEST_H
#define SEGMENTATION_MESSAGE_OBJECT_DETECTIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>

namespace segmentation
{
template <class ContainerAllocator>
struct Object_detectionRequest_
{
  typedef Object_detectionRequest_<ContainerAllocator> Type;

  Object_detectionRequest_()
    : obj_name()
    , img()  {
    }
  Object_detectionRequest_(const ContainerAllocator& _alloc)
    : obj_name(_alloc)
    , img(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _obj_name_type;
  _obj_name_type obj_name;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _img_type;
  _img_type img;





  typedef boost::shared_ptr< ::segmentation::Object_detectionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::segmentation::Object_detectionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Object_detectionRequest_

typedef ::segmentation::Object_detectionRequest_<std::allocator<void> > Object_detectionRequest;

typedef boost::shared_ptr< ::segmentation::Object_detectionRequest > Object_detectionRequestPtr;
typedef boost::shared_ptr< ::segmentation::Object_detectionRequest const> Object_detectionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::segmentation::Object_detectionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::segmentation::Object_detectionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::segmentation::Object_detectionRequest_<ContainerAllocator1> & lhs, const ::segmentation::Object_detectionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.obj_name == rhs.obj_name &&
    lhs.img == rhs.img;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::segmentation::Object_detectionRequest_<ContainerAllocator1> & lhs, const ::segmentation::Object_detectionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace segmentation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::segmentation::Object_detectionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segmentation::Object_detectionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::segmentation::Object_detectionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::segmentation::Object_detectionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segmentation::Object_detectionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segmentation::Object_detectionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::segmentation::Object_detectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "76faba796dec134a8afbf3c2225c081b";
  }

  static const char* value(const ::segmentation::Object_detectionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x76faba796dec134aULL;
  static const uint64_t static_value2 = 0x8afbf3c2225c081bULL;
};

template<class ContainerAllocator>
struct DataType< ::segmentation::Object_detectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "segmentation/Object_detectionRequest";
  }

  static const char* value(const ::segmentation::Object_detectionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::segmentation::Object_detectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string obj_name\n"
"sensor_msgs/Image img\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::segmentation::Object_detectionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::segmentation::Object_detectionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obj_name);
      stream.next(m.img);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Object_detectionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::segmentation::Object_detectionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::segmentation::Object_detectionRequest_<ContainerAllocator>& v)
  {
    s << indent << "obj_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.obj_name);
    s << indent << "img: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.img);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEGMENTATION_MESSAGE_OBJECT_DETECTIONREQUEST_H
