// Generated by gencpp from file segmentation/StretchSegmentationRequest.msg
// DO NOT EDIT!


#ifndef SEGMENTATION_MESSAGE_STRETCHSEGMENTATIONREQUEST_H
#define SEGMENTATION_MESSAGE_STRETCHSEGMENTATIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace segmentation
{
template <class ContainerAllocator>
struct StretchSegmentationRequest_
{
  typedef StretchSegmentationRequest_<ContainerAllocator> Type;

  StretchSegmentationRequest_()
    : object_name()  {
    }
  StretchSegmentationRequest_(const ContainerAllocator& _alloc)
    : object_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _object_name_type;
  _object_name_type object_name;





  typedef boost::shared_ptr< ::segmentation::StretchSegmentationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::segmentation::StretchSegmentationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StretchSegmentationRequest_

typedef ::segmentation::StretchSegmentationRequest_<std::allocator<void> > StretchSegmentationRequest;

typedef boost::shared_ptr< ::segmentation::StretchSegmentationRequest > StretchSegmentationRequestPtr;
typedef boost::shared_ptr< ::segmentation::StretchSegmentationRequest const> StretchSegmentationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::segmentation::StretchSegmentationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::segmentation::StretchSegmentationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::segmentation::StretchSegmentationRequest_<ContainerAllocator1> & lhs, const ::segmentation::StretchSegmentationRequest_<ContainerAllocator2> & rhs)
{
  return lhs.object_name == rhs.object_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::segmentation::StretchSegmentationRequest_<ContainerAllocator1> & lhs, const ::segmentation::StretchSegmentationRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace segmentation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::segmentation::StretchSegmentationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segmentation::StretchSegmentationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::segmentation::StretchSegmentationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::segmentation::StretchSegmentationRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segmentation::StretchSegmentationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segmentation::StretchSegmentationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::segmentation::StretchSegmentationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2f12226348d323c2e5b2031b3da53f1b";
  }

  static const char* value(const ::segmentation::StretchSegmentationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2f12226348d323c2ULL;
  static const uint64_t static_value2 = 0xe5b2031b3da53f1bULL;
};

template<class ContainerAllocator>
struct DataType< ::segmentation::StretchSegmentationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "segmentation/StretchSegmentationRequest";
  }

  static const char* value(const ::segmentation::StretchSegmentationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::segmentation::StretchSegmentationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string object_name\n"
;
  }

  static const char* value(const ::segmentation::StretchSegmentationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::segmentation::StretchSegmentationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StretchSegmentationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::segmentation::StretchSegmentationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::segmentation::StretchSegmentationRequest_<ContainerAllocator>& v)
  {
    s << indent << "object_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.object_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEGMENTATION_MESSAGE_STRETCHSEGMENTATIONREQUEST_H
