- name: "Table_segment"
  require_surface: false
  parent_frame_id: "base_link"
  child_frame_id: "camera_link"
  bounding_frame_id: "base_link"
  segmentation_frame_id: "base_link"
  z_min: -5
  z_max: 5
  x_min: -3.5
  x_max: 3.5
  y_min: -15.0
  y_max: 15.0
  # z_min: 0.7
  # z_max: 0.9
  # x_min: -0.5
  # x_max: 0.5
  # y_min: -1.0
  # y_max: -0.6