// Generated by gencpp from file rail_grasp_calculation_msgs/SampleGraspsResult.msg
// DO NOT EDIT!


#ifndef RAIL_GRASP_CALCULATION_MSGS_MESSAGE_SAMPLEGRASPSRESULT_H
#define RAIL_GRASP_CALCULATION_MSGS_MESSAGE_SAMPLEGRASPSRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseArray.h>

namespace rail_grasp_calculation_msgs
{
template <class ContainerAllocator>
struct SampleGraspsResult_
{
  typedef SampleGraspsResult_<ContainerAllocator> Type;

  SampleGraspsResult_()
    : graspList()  {
    }
  SampleGraspsResult_(const ContainerAllocator& _alloc)
    : graspList(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseArray_<ContainerAllocator>  _graspList_type;
  _graspList_type graspList;





  typedef boost::shared_ptr< ::rail_grasp_calculation_msgs::SampleGraspsResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rail_grasp_calculation_msgs::SampleGraspsResult_<ContainerAllocator> const> ConstPtr;

}; // struct SampleGraspsResult_

typedef ::rail_grasp_calculation_msgs::SampleGraspsResult_<std::allocator<void> > SampleGraspsResult;

typedef boost::shared_ptr< ::rail_grasp_calculation_msgs::SampleGraspsResult > SampleGraspsResultPtr;
typedef boost::shared_ptr< ::rail_grasp_calculation_msgs::SampleGraspsResult const> SampleGraspsResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rail_grasp_calculation_msgs::SampleGraspsResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rail_grasp_calculation_msgs::SampleGraspsResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rail_grasp_calculation_msgs::SampleGraspsResult_<ContainerAllocator1> & lhs, const ::rail_grasp_calculation_msgs::SampleGraspsResult_<ContainerAllocator2> & rhs)
{
  return lhs.graspList == rhs.graspList;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rail_grasp_calculation_msgs::SampleGraspsResult_<ContainerAllocator1> & lhs, const ::rail_grasp_calculation_msgs::SampleGraspsResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rail_grasp_calculation_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rail_grasp_calculation_msgs::SampleGraspsResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rail_grasp_calculation_msgs::SampleGraspsResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rail_grasp_calculation_msgs::SampleGraspsResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rail_grasp_calculation_msgs::SampleGraspsResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rail_grasp_calculation_msgs::SampleGraspsResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rail_grasp_calculation_msgs::SampleGraspsResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rail_grasp_calculation_msgs::SampleGraspsResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b5723f9dc77710d77a9697fd4f04b17c";
  }

  static const char* value(const ::rail_grasp_calculation_msgs::SampleGraspsResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb5723f9dc77710d7ULL;
  static const uint64_t static_value2 = 0x7a9697fd4f04b17cULL;
};

template<class ContainerAllocator>
struct DataType< ::rail_grasp_calculation_msgs::SampleGraspsResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rail_grasp_calculation_msgs/SampleGraspsResult";
  }

  static const char* value(const ::rail_grasp_calculation_msgs::SampleGraspsResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rail_grasp_calculation_msgs::SampleGraspsResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the result\n"
"geometry_msgs/PoseArray graspList          # list of sampled antipodal grasps\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseArray\n"
"# An array of poses with a header for global reference.\n"
"\n"
"Header header\n"
"\n"
"Pose[] poses\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::rail_grasp_calculation_msgs::SampleGraspsResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rail_grasp_calculation_msgs::SampleGraspsResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.graspList);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SampleGraspsResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rail_grasp_calculation_msgs::SampleGraspsResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rail_grasp_calculation_msgs::SampleGraspsResult_<ContainerAllocator>& v)
  {
    s << indent << "graspList: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseArray_<ContainerAllocator> >::stream(s, indent + "  ", v.graspList);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RAIL_GRASP_CALCULATION_MSGS_MESSAGE_SAMPLEGRASPSRESULT_H
