// Auto-generated. Do not edit!

// (in-package fetch_grasp_suggestion.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class SuggestGraspsGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.object_index = null;
    }
    else {
      if (initObj.hasOwnProperty('object_index')) {
        this.object_index = initObj.object_index
      }
      else {
        this.object_index = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type SuggestGraspsGoal
    // Serialize message field [object_index]
    bufferOffset = _serializer.int32(obj.object_index, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type SuggestGraspsGoal
    let len;
    let data = new SuggestGraspsGoal(null);
    // Deserialize message field [object_index]
    data.object_index = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'fetch_grasp_suggestion/SuggestGraspsGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '204f5f3e838d91b73d0c1014a5058dc3';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    int32 object_index                                 # object for which to suggest grasps
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new SuggestGraspsGoal(null);
    if (msg.object_index !== undefined) {
      resolved.object_index = msg.object_index;
    }
    else {
      resolved.object_index = 0
    }

    return resolved;
    }
};

module.exports = SuggestGraspsGoal;
