; Auto-generated. Do not edit!


(cl:in-package fetch_grasp_suggestion-msg)


;//! \htmlinclude ExecuteSelectedGraspGoal.msg.html

(cl:defclass <ExecuteSelectedGraspGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ExecuteSelectedGraspGoal (<ExecuteSelectedGraspGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ExecuteSelectedGraspGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ExecuteSelectedGraspGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name fetch_grasp_suggestion-msg:<ExecuteSelectedGraspGoal> is deprecated: use fetch_grasp_suggestion-msg:ExecuteSelectedGraspGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ExecuteSelectedGraspGoal>) ostream)
  "Serializes a message object of type '<ExecuteSelectedGraspGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ExecuteSelectedGraspGoal>) istream)
  "Deserializes a message object of type '<ExecuteSelectedGraspGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ExecuteSelectedGraspGoal>)))
  "Returns string type for a message object of type '<ExecuteSelectedGraspGoal>"
  "fetch_grasp_suggestion/ExecuteSelectedGraspGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ExecuteSelectedGraspGoal)))
  "Returns string type for a message object of type 'ExecuteSelectedGraspGoal"
  "fetch_grasp_suggestion/ExecuteSelectedGraspGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ExecuteSelectedGraspGoal>)))
  "Returns md5sum for a message object of type '<ExecuteSelectedGraspGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ExecuteSelectedGraspGoal)))
  "Returns md5sum for a message object of type 'ExecuteSelectedGraspGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ExecuteSelectedGraspGoal>)))
  "Returns full string definition for message of type '<ExecuteSelectedGraspGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ExecuteSelectedGraspGoal)))
  "Returns full string definition for message of type 'ExecuteSelectedGraspGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ExecuteSelectedGraspGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ExecuteSelectedGraspGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ExecuteSelectedGraspGoal
))
