// Generated by gencpp from file rail_manipulation_msgs/PrepareGraspRequest.msg
// DO NOT EDIT!


#ifndef RAIL_MANIPULATION_MSGS_MESSAGE_PREPAREGRASPREQUEST_H
#define RAIL_MANIPULATION_MSGS_MESSAGE_PREPAREGRASPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace rail_manipulation_msgs
{
template <class ContainerAllocator>
struct PrepareGraspRequest_
{
  typedef PrepareGraspRequest_<ContainerAllocator> Type;

  PrepareGraspRequest_()
    : graspPose()  {
    }
  PrepareGraspRequest_(const ContainerAllocator& _alloc)
    : graspPose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _graspPose_type;
  _graspPose_type graspPose;





  typedef boost::shared_ptr< ::rail_manipulation_msgs::PrepareGraspRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rail_manipulation_msgs::PrepareGraspRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PrepareGraspRequest_

typedef ::rail_manipulation_msgs::PrepareGraspRequest_<std::allocator<void> > PrepareGraspRequest;

typedef boost::shared_ptr< ::rail_manipulation_msgs::PrepareGraspRequest > PrepareGraspRequestPtr;
typedef boost::shared_ptr< ::rail_manipulation_msgs::PrepareGraspRequest const> PrepareGraspRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rail_manipulation_msgs::PrepareGraspRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rail_manipulation_msgs::PrepareGraspRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rail_manipulation_msgs::PrepareGraspRequest_<ContainerAllocator1> & lhs, const ::rail_manipulation_msgs::PrepareGraspRequest_<ContainerAllocator2> & rhs)
{
  return lhs.graspPose == rhs.graspPose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rail_manipulation_msgs::PrepareGraspRequest_<ContainerAllocator1> & lhs, const ::rail_manipulation_msgs::PrepareGraspRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rail_manipulation_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rail_manipulation_msgs::PrepareGraspRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rail_manipulation_msgs::PrepareGraspRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rail_manipulation_msgs::PrepareGraspRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rail_manipulation_msgs::PrepareGraspRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rail_manipulation_msgs::PrepareGraspRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rail_manipulation_msgs::PrepareGraspRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rail_manipulation_msgs::PrepareGraspRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f48a95707774bb6708f0bd8158e612f7";
  }

  static const char* value(const ::rail_manipulation_msgs::PrepareGraspRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf48a95707774bb67ULL;
  static const uint64_t static_value2 = 0x08f0bd8158e612f7ULL;
};

template<class ContainerAllocator>
struct DataType< ::rail_manipulation_msgs::PrepareGraspRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rail_manipulation_msgs/PrepareGraspRequest";
  }

  static const char* value(const ::rail_manipulation_msgs::PrepareGraspRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rail_manipulation_msgs::PrepareGraspRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseStamped graspPose  # Requested grasp pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::rail_manipulation_msgs::PrepareGraspRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rail_manipulation_msgs::PrepareGraspRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.graspPose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PrepareGraspRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rail_manipulation_msgs::PrepareGraspRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rail_manipulation_msgs::PrepareGraspRequest_<ContainerAllocator>& v)
  {
    s << indent << "graspPose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.graspPose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RAIL_MANIPULATION_MSGS_MESSAGE_PREPAREGRASPREQUEST_H
