// Generated by gencpp from file rail_manipulation_msgs/SuggestGrasps.msg
// DO NOT EDIT!


#ifndef RAIL_MANIPULATION_MSGS_MESSAGE_SUGGESTGRASPS_H
#define RAIL_MANIPULATION_MSGS_MESSAGE_SUGGESTGRASPS_H

#include <ros/service_traits.h>


#include <rail_manipulation_msgs/SuggestGraspsRequest.h>
#include <rail_manipulation_msgs/SuggestGraspsResponse.h>


namespace rail_manipulation_msgs
{

struct SuggestGrasps
{

typedef SuggestGraspsRequest Request;
typedef SuggestGraspsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SuggestGrasps
} // namespace rail_manipulation_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rail_manipulation_msgs::SuggestGrasps > {
  static const char* value()
  {
    return "2e99096b2d9e72ab0621b90ffe5e5f64";
  }

  static const char* value(const ::rail_manipulation_msgs::SuggestGrasps&) { return value(); }
};

template<>
struct DataType< ::rail_manipulation_msgs::SuggestGrasps > {
  static const char* value()
  {
    return "rail_manipulation_msgs/SuggestGrasps";
  }

  static const char* value(const ::rail_manipulation_msgs::SuggestGrasps&) { return value(); }
};


// service_traits::MD5Sum< ::rail_manipulation_msgs::SuggestGraspsRequest> should match
// service_traits::MD5Sum< ::rail_manipulation_msgs::SuggestGrasps >
template<>
struct MD5Sum< ::rail_manipulation_msgs::SuggestGraspsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rail_manipulation_msgs::SuggestGrasps >::value();
  }
  static const char* value(const ::rail_manipulation_msgs::SuggestGraspsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rail_manipulation_msgs::SuggestGraspsRequest> should match
// service_traits::DataType< ::rail_manipulation_msgs::SuggestGrasps >
template<>
struct DataType< ::rail_manipulation_msgs::SuggestGraspsRequest>
{
  static const char* value()
  {
    return DataType< ::rail_manipulation_msgs::SuggestGrasps >::value();
  }
  static const char* value(const ::rail_manipulation_msgs::SuggestGraspsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rail_manipulation_msgs::SuggestGraspsResponse> should match
// service_traits::MD5Sum< ::rail_manipulation_msgs::SuggestGrasps >
template<>
struct MD5Sum< ::rail_manipulation_msgs::SuggestGraspsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rail_manipulation_msgs::SuggestGrasps >::value();
  }
  static const char* value(const ::rail_manipulation_msgs::SuggestGraspsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rail_manipulation_msgs::SuggestGraspsResponse> should match
// service_traits::DataType< ::rail_manipulation_msgs::SuggestGrasps >
template<>
struct DataType< ::rail_manipulation_msgs::SuggestGraspsResponse>
{
  static const char* value()
  {
    return DataType< ::rail_manipulation_msgs::SuggestGrasps >::value();
  }
  static const char* value(const ::rail_manipulation_msgs::SuggestGraspsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RAIL_MANIPULATION_MSGS_MESSAGE_SUGGESTGRASPS_H
